import Head from "next/head";
import { GetServerSidePropsContext } from "next";
import { ResponseApi } from "@/models/ResponseApi";
import { MainCarousel } from "@/components/MainCarousel";
import { Box, Container } from "@chakra-ui/react";
import { InformationBox } from "@/components/InformationBox";
import { ProductCarousel } from "@/components/ProductCarousel";
import { Header } from "@/components/Header";
import { GroupBanner } from "@/components/GroupBanner";
import { Footer } from "@/components/Footer";
import DemoHeader from "@/components/demoHeader";
type Props = {
  eccoData: ResponseApi;
};
export default function Home({ eccoData }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DemoHeader></DemoHeader>
        <Box className="contenedorPr">
          <MainCarousel data={eccoData.Data.Banner_main}></MainCarousel>
          <Container>
            <InformationBox></InformationBox>
          </Container>
          <GroupBanner data={eccoData.Data.Banner_group}></GroupBanner>
          <ProductCarousel data={eccoData}></ProductCarousel>
        </Box>
      </main>
      <Footer></Footer>
    </>
  );
}
export async function getServerSideProps(context: GetServerSidePropsContext) {
  const eccoData: any = await fetch(
    `${process.env.API_URL}/loadEcommerce`
  ).then((res) => res.json());
  return {
    props: { eccoData },
  };
}
